# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161006_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_user_friends_+', to=settings.AUTH_USER_MODEL, verbose_name='Friends'),
        ),
    ]
